#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = mod

# The header files we want copied
HEADERS = modform.h modgen.h stmform.h mtmform.h

# The source files that make the lib
SOURCE = modgen.cpp modform.cpp stmform.cpp mtmform.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
