#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = ptm

# The header files we want copied
HEADERS = ptmform.h

# The source files that make the lib
SOURCE = ptmform.cpp ptmplay.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
