#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = xm

# The header files we want copied
HEADERS = xmform.h

# The source files that make the lib
SOURCE = xmform.cpp xmplay.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
