#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = far

# The header files we want copied
HEADERS = farform.h

# The source files that make the lib
SOURCE = farform.cpp farplay.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
