#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = fileout

# The header files we want copied
HEADERS = au.h wav.h raw.h

# The source files that make the lib
SOURCE = au.cpp raw.cpp wav.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
