#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = ult

# The header files we want copied
HEADERS = ultform.h

# The source files that make the lib
SOURCE = ultform.cpp ultplay.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
