#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = archiver

# The header files we want copied
HEADERS = gzip.h

# The source files that make the lib
SOURCE = gzip.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
