#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = simpfilt

# The header files we want copied
HEADERS = simpfilt.h

# The source files that make the lib
SOURCE = simpfilt.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
