#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = ossdsp

# The header files we want copied
HEADERS = ossdsp.h

# The source files that make the lib
SOURCE = ossdsp.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
