#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
PROGRAM = test

# The source files that make the exe
SOURCE = test.cpp

# Libraries
# Oddly these have to be in the reverse order of their dependancies. 
# baseset depends on utils and everything else depends on baseset
LIBS = utils

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
