#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = baseset

# The header files we want copied
HEADERS = flags.h muse.h errors.h
HEADERS += outputbs.h formatbs.h efxfiltr.h timebuf.h songlist.h

# The source files that make the lib
SOURCE = outputbs.cpp formatbs.cpp efxfiltr.cpp timebuf.cpp songlist.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
