#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = mixerbase

# The header files we want copied
HEADERS = dac.h mix.h

# The source files that make the lib
SOURCE = mixers.cpp mixercom.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
