#!/usr/bin/make -sf
# -*- make -*-

# Define the library name
LIBRARY = it

# The header files we want copied
HEADERS = itform.h

# The source files that make the lib
SOURCE = itform.cpp itplay.cpp

# This does the rest automagically!
REL = ..
include $(REL)/makedefs.gmk
	
